In [ ]:
Sub SaveSheetAsCS()
    Dim ws As Worksheet
    Set ws = ThisWorkbook.Sheets("Sheet1")  ' 저장하고 싶은 시트 이름으로 설정하세요.
    Dim savePath As String
    savePath = "D:\시설\유지\'24년4월 조건요약.cs"  ' 파일 이름을 원하는 대로 설정하세요.

    ' CSV로 저장하듯이 처리하되 확장자만 .cs로 변경
    ws.SaveAs Filename:=savePath, FileFormat:=xlCSV, CreateBackup:=False
End Sub

In [1]:
import pandas as pd

# 파일 경로 설정, 확장자가 .cs
file_path = 'D:/시설/유지/24년 4월 유지가입자.cs'

# CSV 파일 읽기, 헤더 및 데이터 타입 경고 처리
df = pd.read_csv(file_path, encoding='cp949', low_memory=False)

# 헤더만 출력, 보기 좋게 줄바꿈하여 표시
for column in df.columns:
    print(column)

관리본부코드
관리본부명
관리지사코드
관리지사명
고객번호
고객명
계약번호
계약자명
서비스번호
서비스(대)
서비스(중)
서비스(소)
영상전환일
상호
고객구분
사업용구분
주민등록번호
사업자번호
계약상태(대)
계약상태(중)
서비스상태(대)
서비스상태(중)
접속전화번호
설치우편번호
설치주소
견적월정료
월정료
할인율
계약개월수
월정료면제사유
면제시작일
면제종료일
계약보증금
보증금면제사유
판매상품비
견적설치공사비
설치공사할부개월
계약공사비
면제공사비
실징수액
계약시작일
계약종료일
영업구분
추천구분
추천경로
영업본부코드
영업본부명
영업지사코드
영업지사명
영업지점명
영업자사번
영업자명
영업자연락처
모집유형
영업채널
가망고객번호
추천본부코드
추천본부명
추천지사코드
추천지사명
유통망대분류
유통망중분류
유통망소분류
추천자사번
추천자명
추천자유형
추천채널
정보제공자부서
정보제공자사번
정보제공자명
정보제공자연락처
청구본부코드
청구본부명
청구지사코드
청구지사명
청구자명
합산여부
수납구분
세금계산서발행여부
계산서발행여부
선후납구분
청구번호
청구전화번호
청구우편번호
청구주소
청약일자
청약취소일자
공사희망일
공사완료일
준공완료일
관제개통일
서비스개시일
서비스재개시일
공사의뢰유형
회선방식(대)
회선방식(중)
MUX
전용회선번호
MIN번호
정지시작일자
해지일자
종목
업태
업종_대
업종_중
보험등급
비고
결합구분
결합상품명
결합약정개월수
결합시작일
금융기관코드
면책구분
타사전환
이전고객번호
E-MAIL
담당자
휴대폰
전입신규여부
고객추가정보
계약최초서비스게시일
청약취소사유
계약본부
계약지사
매출본사
매출인정구분
구역정보
구역담당지점
구역담당영업사원
구역담당영업사원명
설치공사비
시설구분
요금구분
선장품
브랜드
고객계약유형
A/S운용기간
판매할부개월
실적본부
실적지사
실적최초등록일
실적구분
영업구역정보
기술구역정보
해지코드
해지사유
사용일수
사용개월수
최종계약구분
영업이익율
공헌이익율
KT마스터ID
BIZNARU계약ID
정지희망종료일
신규PP
SW주장치안정화DB
매출구분
영업본부2
영업지사2
실적채널
실적부서
직접/추천
무인매장구분
무인매장업종구분
판매구분
KTT월정료(조정)
KT월정료(조정)
고알프
제외사유
정지기간
정지유형

In [5]:
import pandas as pd
from IPython.display import display, HTML

# 파일 경로 설정, 확장자가 .cs
file_path = 'D:/시설/유지/24년 4월 유지가입자.cs'

# CSV 파일 읽기, 헤더 및 데이터 타입 경고 처리
df = pd.read_csv(file_path, encoding='cp949', low_memory=False)

# 조회할 조건 설정
contract_number = '50129703'
partial_business_name = ''  # 사용자가 원하는 상호 일부 입력

# 조건에 맞는 데이터 필터링, 대소문자 구분 없이 검색
filtered_data = df[
    (df['계약번호'].astype(str) == contract_number) &
    (df['상호'].str.contains(partial_business_name, na=False, case=False))
][['청구번호', '계약번호', '상호', 'KTT월정료(조정)', '서비스상태(중)', '정지시작일자', '서비스(중)', '서비스(소)', '주민등록번호', '사업자번호', '보험등급', '영업자명']]

# 조건에 맞는 데이터만 표시
display(HTML(filtered_data.to_html()))

In [7]:
!pip install ipywidgets

Looking in indexes: https://pypi.org/simple/
Collecting ipywidgets
  Downloading ipywidgets-8.1.2-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: comm>=0.1.3 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipywidgets) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipywidgets) (8.21.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipywidgets) (5.14.1)
Collecting widgetsnbextension~=4.0.10 (from ipywidgets)
  Downloading widgetsnbextension-4.0.10-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab-widgets~=3.0.10 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.10-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: decorator in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (2.17.2)
Requirement already satisfied: stack-data in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\user\appdata\roaming\python\python312\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\user\appdata\roaming\python\python312\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.1)
Requirement already satisfied: pure-eval in c:\users\user\appdata\roaming\python\python312\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: six>=1.12.0 in c:\users\user\anaconda3\envs\python_v1\lib\site-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)
Downloading ipywidgets-8.1.2-py3-none-any.whl (139 kB)
   ---------------------------------------- 0.0/139.4 kB ? eta -:--:--
   -------------------------------------- - 133.1/139.4 kB 7.7 MB/s eta 0:00:01
   ---------------------------------------- 139.4/139.4 kB 1.7 MB/s eta 0:00:00
Downloading jupyterlab_widgets-3.0.10-py3-none-any.whl (215 kB)
   ---------------------------------------- 0.0/215.0 kB ? eta -:--:--
   -------------------------------------- - 204.8/215.0 kB ? eta -:--:--
   ---------------------------------------- 215.0/215.0 kB 3.3 MB/s eta 0:00:00
Downloading widgetsnbextension-4.0.10-py3-none-any.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.3 MB 6.5 MB/s eta 0:00:01
   -------- ------------------------------- 0.5/2.3 MB 6.0 MB/s eta 0:00:01
   -------------- ------------------------- 0.8/2.3 MB 5.2 MB/s eta 0:00:01
   ------------------ --------------------- 1.1/2.3 MB 5.2 MB/s eta 0:00:01
   ----------------------- ---------------- 1.3/2.3 MB 5.0 MB/s eta 0:00:01
   -------------------------- ------------- 1.5/2.3 MB 5.0 MB/s eta 0:00:01
   ------------------------------ --------- 1.7/2.3 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 2.1/2.3 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  2.3/2.3 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 4.4 MB/s eta 0:00:00
Installing collected packages: widgetsnbextension, jupyterlab-widgets, ipywidgets
Successfully installed ipywidgets-8.1.2 jupyterlab-widgets-3.0.10 widgetsnbextension-4.0.10

In [39]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# 파일 경로 설정
file_path = 'D:/시설/유지/24년 4월 유지가입자.cs'

# CSV 파일 읽기, 모든 데이터를 문자열로 처리
df = pd.read_csv(file_path, encoding='cp949', dtype=str)
df.fillna('', inplace=True)  # NaN 값을 빈 문자열로 대체

# 입력 위젯 설정
input_fields = {
    '계약번호': '계약 번호 입력',
    '상호': '상호 부분 입력',
    '고객명': '고객명 부분 입력',
    '설치주소': '설치 주소 부분 입력',
    '관리본부명': '관리 본부명 입력',
    '관리지사명': '관리 지사명 입력',
    # '영업구역정보': '영업 구역 정보 입력',
    '영업자명': '구역 담당 영업사원 입력'
}

inputs = {key: widgets.Text(placeholder=desc, description=f'{key}:') for key, desc in input_fields.items()}

# 체크박스와 컬럼 이름 구성
checkboxes = [widgets.Checkbox(value=False, description=label) for label in df.columns]
checkbox_container = widgets.VBox(children=[widgets.HBox(checkboxes[i:i+5]) for i in range(0, len(checkboxes), 5)])

# 전체 선택/해제 버튼
toggle_buttons = widgets.ToggleButtons(
    options=['Select All', 'Deselect All'],
    description='Check:',
    disabled=False,
    button_style='',  # 'success', 'info', 'warning', 'danger' or ''
)

def toggle_checkboxes(change):
    if change['new'] == 'Select All':
        for checkbox in checkboxes:
            checkbox.value = True
    elif change['new'] == 'Deselect All':
        for checkbox in checkboxes:
            checkbox.value = False
    toggle_buttons.value = None  # Reset toggle button state

toggle_buttons.observe(toggle_checkboxes, 'value')

# 실행 버튼
run_button = widgets.Button(description='조회 실행', button_style='success', icon='search')
# 저장 버튼
save_button = widgets.Button(description='Excel로 저장', button_style='info', icon='save')

output = widgets.Output()

def run_query(b):
    with output:
        clear_output(wait=True)
        try:
            # 필터링 조건 적용
            condition = True
            for field, widget in inputs.items():
                if widget.value.strip():  # 입력값에서 공백 제거
                    condition &= df[field].str.contains(widget.value.strip(), case=False)
            filtered_data = df.loc[condition]
            selected_columns = [cb.description for cb in checkboxes if cb.value]
            if not selected_columns:
                raise ValueError("결과로 표시할 컬럼을 선택하세요.")
            if filtered_data.empty:
                raise ValueError("조회된데이터가 없습니다. 조건을 확인해주세요.")
            styled_html = filtered_data[selected_columns].to_html(escape=False, classes='styledTable')
            styled_css = "<style>.styledTable {width: 100%; border-collapse: collapse;} .styledTable th, .styledTable td {border: 1px solid #dddddd; padding: 8px; text-align: left;} .styledTable tr:nth-child(even) {background-color: #f7f7f7;} .styledTable tr:nth-child(odd) {background-color: #e7e7e7;}</style>"
            display(HTML(styled_css + styled_html))
        except Exception as e:
            display(HTML(f"<div style='color: red;'>Error: {e}</div>"))

def save_to_excel(b):
    try:
        if 'filtered_data' in globals() and 'selected_columns' in globals():
            filtered_data[selected_columns].to_excel('추출리스트.xlsx', index=False)
            with output:
                clear_output(wait=True)
                display(HTML("<div style='color: green;'>Data successfully saved to '추출리스트.xlsx'</div>"))
        else:
            raise ValueError("저장할 데이터가 없습니다. 먼저 조회를 실행하세요.")
    except Exception as e:
        with output:
            clear_output(wait=True)
            display(HTML(f"<div style='color: red;'>Error saving file: {e}</div>"))

# 이벤트 핸들러 연결
run_button.on_click(run_query)
save_button.on_click(save_to_excel)

# 입력 필드와 버튼을 같은 행에 배치
input_row = widgets.HBox([widgets.VBox([inputs[field] for field in inputs.keys()]), run_button, save_button])

# 체크박스 토글과 컬럼 선택을 관리하는 행
checkbox_toggle_row = widgets.HBox([toggle_buttons])

# UI 구성
ui = widgets.VBox([input_row, checkbox_container, checkbox_toggle_row, output])
display(ui)

VBox(children=(HBox(children=(VBox(children=(Text(value='', description='계약번호:', placeholder='계약 번호 입력'), Text…

In [1]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# 파일 경로 설정
# file_path = '/Users/heebonpark/Downloads/24년 4월 유지가입자.cs'
file_path = 'D:/시설/유지/24년 4월 유지가입자.cs'


# CSV 파일 읽기, 모든 데이터를 문자열로 처리
df = pd.read_csv(file_path, encoding='cp949', dtype=str)
df.fillna('', inplace=True)  # NaN 값을 빈 문자열로 대체

# 입력 위젯 설정
input_fields = {
    '계약번호': '계약 번호 입력',
    '상호': '상호 부분 입력',
    '실적최초등록일': '실적최초등록일 부분 입력',
    '고객명': '고객명 부분 입력',
    '설치주소': '설치 주소 부분 입력',
    '관리본부명': '관리 본부명 입력',
    '관리지사명': '관리 지사명 입력',
    '시설구분': '시설대상 입력',
    '요금구분': '요금대상 입력',
    '제외사유': '제외사유 대상입력',
    # '영업구역정보': '영업 구역 정보 입력',
    '영업자명': '구역 담당 영업사원 입력',
   '무인매장구분': '무인매장구분 입력',
   '무인매장업종구분': '무인매장업종구분 입력'
   
    
    
}


# 제외할 컬럼 목록 정의
excluded_columns = [
    "관리본부코드", "관리지사코드", "영상전환일", "서비스상태(대)", "서비스상태(중)",
    "접속전화번호", "설치우편번호", "견적월정료", "할인율", "월정료면제사유",
    "면제시작일", "면제종료일", "계약보증금", "보증금면제사유", "판매상품비", "견적설치공사비",
    "설치공사할부개월", "계약공사비", "면제공사비", "실징수액", "추천구분", "영업본부코드",
    "영업지사코드", "영업지점명", "모집유형", "추천본부코드", "추천본부명", "추천지사코드",
    "유통망소분류", "추천채널", "정보제공자부서", "정보제공자사번", "정보제공자연락처",
    "청구본부코드", "청구지사코드", "청구자명", "세금계산서발행여부", "계산서발행여부", "선후납구분",
    "청구전화번호", "청구우편번호", "청약일자", "청약취소일자", "공사희망일", "공사완료일",
    "준공완료일", "관제개통일", "서비스개시일", "서비스재개시일", "공사의뢰유형", "회선방식(대)",
    "MUX", "전용회선번호", "MIN번호", "해지일자", "업종_대", "업종_중",
    "보험등급", "비고", "결합구분", "결합상품명", "결합약정개월수", "결합시작일", "금융기관코드",
    "면책구분", "타사전환", "이전고객번호", "전입신규여부", "고객추가정보", "청약취소사유",
    "정지기간", "정지유형", "설치공사비", "영업이익율", "공헌이익율","SW주장치안정화DB",
    "선장품", "브랜드", "A/S운용기간", "고객계약유형","판매할부개월",
    "최종계약구분", "KT마스터ID", "BIZNARU계약ID", "정지희망종료일", "신규PP","직접/추천",
    "판매구분"
   

]

# 데이터프레임에서 이 컬럼들을 제거
df = df.drop(columns=[col for col in excluded_columns if col in df.columns])

inputs = {key: widgets.Text(placeholder=desc, description=f'{key}:') for key, desc in input_fields.items()}

# 체크박스와 컬럼 이름 구성
checkboxes = [widgets.Checkbox(value=False, description=label) for label in df.columns]
checkbox_container = widgets.VBox(children=[widgets.HBox(checkboxes[i:i+5]) for i in range(0, len(checkboxes), 5)])

# 전체 선택/해제 버튼
toggle_buttons = widgets.ToggleButtons(
    options=['Select All', 'Deselect All'],
    description='Check:',
    disabled=False,
    button_style='',  # 'success', 'info', 'warning', 'danger' or ''
)

def toggle_checkboxes(change):
    if change['new'] == 'Select All':
        for checkbox in checkboxes:
            checkbox.value = True
    elif change['new'] == 'Deselect All':
        for checkbox in checkboxes:
            checkbox.value = False
    toggle_buttons.value = None  # Reset toggle button state

toggle_buttons.observe(toggle_checkboxes, 'value')

# 실행 버튼
run_button = widgets.Button(description='조회 실행', button_style='success', icon='search')
# 저장 버튼
save_button = widgets.Button(description='Excel로 저장', button_style='info', icon='save')

output = widgets.Output()

def run_query(b):
    global filtered_data, selected_columns
    with output:
        clear_output(wait=True)
        try:
            condition = True
            for field, widget in inputs.items():
                if widget.value.strip():
                    condition &= df[field].str.contains(widget.value.strip(), case=False)
            filtered_data = df.loc[condition]
            selected_columns = [cb.description for cb in checkboxes if cb.value]
            if not selected_columns:
                raise ValueError("결과로 표시할 컬럼을 선택하세요.")
            if filtered_data.empty:
                raise ValueError("조회된 데이터가 없습니다. 조건을 확인해주세요.")
            styled_html = filtered_data[selected_columns].to_html(escape=False, classes='styledTable')
            styled_css = """
            <style>
                .styledTable {
                    width: 100%;
                    border-collapse: collapse;
                    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
                    background-color: #f9f9f9;
                    color: #333;
                }
                .styledTable th, .styledTable td {
                    border: 1px solid #dddddd;
                    padding: 8px;
                    text-align: left;
                }
                .styledTable th {
                    background-color: #f2f2f2;
                    color: #333;
                }
                .styledTable tr:nth-child(even) {
                    background-color: #ffffff;
                }
                .styledTable tr:nth-child(odd) {
                    background-color: #f7f7f7;
                }
                .styledTable tr:hover {
                    background-color: #f1f1f1;
                }
            </style>
            """
            display(HTML(styled_css + styled_html))
        except Exception as e:
            display(HTML(f"<div style='color: red;'>Error: {e}</div>"))


def save_to_excel(b):
    global filtered_data, selected_columns
    try:
        if 'filtered_data' in globals() and 'selected_columns' in globals():
            filtered_data[selected_columns].to_excel('추출리스트.xlsx', index=False)
            with output:
                clear_output(wait=True)
                display(HTML("<div style='color: green;'>Data successfully saved to '무인추출리스트.xlsx'</div>"))
        else:
            raise ValueError("저장할 데이터가 없습니다. 먼저 조회를 실행하세요.")
    except Exception as e:
        with output:
            clear_output(wait=True)
            display(HTML(f"<div style='color: red;'>Error saving file: {e}</div>"))

# 이벤트 핸들러 연결
run_button.on_click(run_query)
save_button.on_click(save_to_excel)

# 입력 필드와 버튼을 같은 행에 배치
input_row = widgets.HBox([widgets.VBox([inputs[field] for field in inputs.keys()]), run_button, save_button])

# 체크박스 토글과 컬럼 선택을 관리하는 행
checkbox_toggle_row = widgets.HBox([toggle_buttons])

# UI 구성
ui = widgets.VBox([input_row, checkbox_container, checkbox_toggle_row, output])
display(ui)

KeyboardInterrupt:

In [1]:
import pandas as pd

# 데이터 로드 및 초기 처리 예시
# df = pd.read_csv('file_path.csv', encoding='cp949')
# df.fillna('', inplace=True)  # NaN 값을 빈 문자열로 대체

# 데이터 타입 변환
df['계약번호'] = pd.to_numeric(df['계약번호'], errors='coerce')
df['KTT월정료(조정)'] = pd.to_numeric(df['KTT월정료(조정)'], errors='coerce')

# 제외사유가 빈 문자열이 아닌 경우 제외
df = df[df['제외사유'] == '']

# 본부별 지사 매핑
본부_지정 = {
    '강남/서부본부': ['강남지사', '강동지사', '강서지사', '관악지사', '부천지사', '분당지사', '수원지사', '안산지사', '안양지사', '용인지사', '인천지사', '평택지사'],
    '강북/강원본부': ['중앙지사', '강북지사', '고양지사', '서대문지사', '의정부지사', '남양주지사', '원주지사', '춘천고객지원팀',  '강릉지사'],
    '대구/경북본부': ['대구지사', '동대구지사', '수성지사', '구미지사', '포항지사'],
    '부산/경남본부': ['동부산지사', '남부산지사', '서부산지사', '울산지사', '김해지사', '창원지사', '진주지사'],
    '전남/전북본부': ['광주지사', '북광주지사', '목포지사', '순천지사', '전주지사', '익산지사', '제주지사'],
    '충남/충북본부': ['대전지사', '서대전지사', '천안지사', '충남서부지사', '충북지사']
}

# 본부별 DataFrame 생성
dataframes = {}
for 본부, 지사리스트 in 본부_지정.items():
    본부_df = df[df['관리지사명'].isin(지사리스트)]
    본부_df_grouped = 본부_df.groupby('관리지사명').agg(
        계약번호_행개수=('계약번호', 'size'),
        KTT월정료_합계=('KTT월정료(조정)', 'sum')
    ).reset_index()
    본부_df_grouped['KTT월정료_합계'] = 본부_df_grouped['KTT월정료_합계'].apply(lambda x: f"{x:,.0f}")

    # 소계 추가
    소계 = 본부_df_grouped.sum(numeric_only=True)
    소계['관리지사명'] = '소계'
    소계_df = pd.DataFrame([소계], columns=본부_df_grouped.columns)
    본부_df_final = pd.concat([본부_df_grouped, 소계_df], ignore_index=True)

    dataframes[본부] = 본부_df_final

# 스타일링 함수 정의
def style_specific(df):
    return df.style.set_table_styles([
        {'selector': 'th', 'props': [('background-color', '#f4f4f4'), ('color', 'black')]},
        {'selector': 'td', 'props': [('border-color', 'lightgray')]}
    ]).set_properties(**{
        'text-align': 'left',
        'border-color': 'lightgray',
        'border-width': '1px',
        'border-style': 'solid'
    })

# 본부별로 출력 (예시)
for 본부, 본부_df in dataframes.items():
    print(f"--- {본부} ---")
    display(style_specific(본부_df))

NameError: name 'df' is not defined

In [13]:
import pandas as pd

# 데이터 로드 및 초기 처리 예시
# df = pd.read_csv('file_path.csv', encoding='cp949')
# df.fillna('', inplace=True)  # NaN 값을 빈 문자열로 대체

# 데이터 타입 변환
df['계약번호'] = pd.to_numeric(df['계약번호'], errors='coerce')
df['KTT월정료(조정)'] = pd.to_numeric(df['KTT월정료(조정)'], errors='coerce')



# 본부별 지사 매핑
본부_지정 = {
    '강남/서부본부': ['강남지사', '강동지사', '강서지사', '관악지사', '부천지사', '분당지사', '수원지사', '안산지사', '안양지사', '용인지사', '인천지사', '평택지사'],
    '강북/강원본부': ['중앙지사', '강북지사', '고양지사', '서대문지사', '의정부지사', '남양주지사', '원주지사', '춘천고객지원팀',  '강릉지사'],
    '대구/경북본부': ['대구지사', '동대구지사', '수성지사', '구미지사', '포항지사'],
    '부산/경남본부': ['동부산지사', '남부산지사', '서부산지사', '울산지사', '김해지사', '창원지사', '진주지사'],
    '전남/전북본부': ['광주지사', '북광주지사', '목포지사', '순천지사', '전주지사', '익산지사', '제주지사'],
    '충남/충북본부': ['대전지사', '서대전지사', '천안지사', '충남서부지사', '충북지사']
}

# 본부별 DataFrame 생성
dataframes = {}
for 본부, 지사리스트 in 본부_지정.items():
    본부_df = df[df['관리지사명'].isin(지사리스트)]
    본부_df_grouped = 본부_df.groupby('관리지사명').agg(
        계약번호_행개수=('계약번호', 'size'),
        KTT월정료_합계=('KTT월정료(조정)', 'sum')
    ).reset_index()
    본부_df_grouped['KTT월정료_합계'] = 본부_df_grouped['KTT월정료_합계'].apply(lambda x: f"{x:,.0f}")

    # 소계 추가
    소계 = 본부_df_grouped.sum(numeric_only=True)
    소계['관리지사명'] = '소계'
    소계_df = pd.DataFrame([소계], columns=본부_df_grouped.columns)
    본부_df_final = pd.concat([본부_df_grouped, 소계_df], ignore_index=True)

    dataframes[본부] = 본부_df_final

# 스타일링 함수 정의
def style_specific(df):
    return df.style.set_table_styles([
        {'selector': 'th', 'props': [('background-color', '#f4f4f4'), ('color', 'black')]},
        {'selector': 'td', 'props': [('border-color', 'lightgray')]}
    ]).set_properties(**{
        'text-align': 'left',
        'border-color': 'lightgray',
        'border-width': '1px',
        'border-style': 'solid'
    })

# 본부별로 출력 (예시)
for 본부, 본부_df in dataframes.items():
    print(f"--- {본부} ---")
    display(style_specific(본부_df))

--- 강남/서부본부 ---

--- 강북/강원본부 ---

--- 대구/경북본부 ---

--- 부산/경남본부 ---

--- 전남/전북본부 ---

--- 충남/충북본부 ---

In [2]:
# 앞에서 부터 데이터 검색
df.head()

,관리본부명,관리지사명,고객번호,고객명,계약번호,계약자명,서비스번호,서비스(대),서비스(중),서비스(소),...,사용개월수,매출구분,영업본부2,영업지사2,실적채널,실적부서,KTT월정료(조정),KT월정료(조정),고알프,제외사유
0,서부본부,강서지사,276368,문*권,20296654,문*권,20296654,기본서비스,텔레캅아이,ktt OCT 가드(DVR),...,,,,,SP,강서지사,40914,0,N,
1,서부본부,인천지사,30624766,김*임,20296805,김*임,20296805,기본서비스,텔레캅아이,ktt OCT 가드(DVR),...,,,,,SP,인천지사,56000,0,N,
2,강남/서부본부,평택지사,276716,강*욱,20297064,강*욱,20297064,기본서비스,GiGAeyes Basic,GiGAeyes Basic,...,,,,,SP,평택지사,49000,0,N,
3,대구/경북본부,대구지사,276906,김*희,20297924,김*희,20297924,기본서비스,텔레캅아이,ktt OCT 가드(DVR),...,,,,,SP,대구지사,75000,0,N,
4,강남/서부본부,분당지사,30331349,이*숙,20296947,이*숙,20296947,기본서비스,텔레캅아이,ktt OCT 가드(DVR),...,,,,,SP,분당지사,55000,0,N,

In [29]:
# 뒤에서 부터 데이터 검색
df.tail()

,관리본부명,관리지사명,고객번호,고객명,계약번호,계약자명,서비스번호,서비스(대),서비스(중),서비스(소),...,매출구분,영업본부2,영업지사2,실적채널,실적부서,무인매장구분,KTT월정료(조정),KT월정료(조정),고알프,제외사유
383379,강남/서부본부,강동지사,30439523,(SG)주식회사두일아이엔씨,50941643,(SG)주식회사두일아이엔씨,61129548,기본서비스,GiGAeyes Basic,GiGAeyes Basic,...,,,,SP,강동지사,유인매장,50000,0,N,
383380,부산/경남본부,울산지사,182455,권*현,11223356,권*현,11223356,기본서비스,텔레캅아이,ktt OCT 가드(DVR),...,,,,SP,울산지사,유인매장,65000,0,N,
383381,강북/강원본부,고양지사,30060895,전*경,11231717,전*경,11231717,기본서비스,GiGAeyes Basic,GiGAeyes Basic,...,,,,SP,고양지사,,45000,0,N,
383382,강남/서부본부,용인지사,178230,이*국,11169747,이*국,11169747,기본서비스,텔레캅아이,ktt OCT 가드(DVR),...,,,,SP,용인지사,,64000,0,N,
383383,대구/경북본부,대구지사,172643,동부화재해상보험(주),50164326,동부화재해상보험(주),60197694,기본서비스,GiGAeyes Basic,GiGAeyes Basic,...,AM(영업),,,SP,대구지사,유인매장,38000,0,N,

In [3]:
df.describe()

,관리본부명,관리지사명,고객번호,고객명,계약번호,계약자명,서비스번호,서비스(대),서비스(중),서비스(소),...,사용개월수,매출구분,영업본부2,영업지사2,실적채널,실적부서,KTT월정료(조정),KT월정료(조정),고알프,제외사유
count,383384,383384,383384,383384,383384,383384,383384,383384,383384,383384,...,383384,383384,383384,383384,383384,383384,383384,383384,383384,383384
unique,8,45,312573,53145,374350,54630,383384,1,4,79,...,1,6,1,1,4,157,9897,5931,2,19
top,전남/전북본부,원주지사,90046833,노틸러스효성㈜,51942709,주**사자비스넷,20296654,기본서비스,텔레캅아이,GiGAeyes guard+(DVR),...,,,,,SP,,22100,0,N,
freq,57326,12192,8519,8783,273,7537,1,383384,325641,50853,...,383384,341914,383384,383384,319924,26110,27337,271314,349076,358549

In [ ]:
# 원하는 데이터 뽑기

In [19]:
df.columns

Index(['관리본부명', '관리지사명', '고객번호', '고객명', '계약번호', '계약자명', '서비스번호', '서비스(대)',
       '서비스(중)', '서비스(소)', '상호', '고객구분', '사업용구분', '주민등록번호', '사업자번호', '계약상태(대)',
       '계약상태(중)', '설치주소', '월정료', '계약개월수', '계약시작일', '계약종료일', '영업구분', '추천경로',
       '영업본부명', '영업지사명', '영업자사번', '영업자명', '영업자연락처', '영업채널', '가망고객번호', '추천지사명',
       '유통망대분류', '유통망중분류', '추천자사번', '추천자명', '추천자유형', '정보제공자명', '청구본부명',
       '청구지사명', '합산여부', '수납구분', '청구번호', '청구주소', '정지시작일자', '종목', '업태', 'E-MAIL',
       '담당자', '휴대폰', '계약최초서비스게시일', '계약본부', '계약지사', '매출본사', '매출인정구분', '구역정보',
       '구역담당지점', '구역담당영업사원', '구역담당영업사원명', '시설구분', '요금구분', '실적본부', '실적지사',
       '실적최초등록일', '실적구분', '영업구역정보', '기술구역정보', '해지코드', '해지사유', '사용일수', '사용개월수',
       '매출구분', '영업본부2', '영업지사2', '실적채널', '실적부서', 'KTT월정료(조정)', 'KT월정료(조정)',
       '고알프', '제외사유'],
      dtype='object')

In [21]:
# df의 컬럼명을 필요한 컬럼과 원하는 순서로 리스트화 합니다.
new_columns = ['관리본부명', '관리지사명', '고객번호', '고객명', '계약번호', '서비스번호', '서비스(대)',
       '서비스(중)', '서비스(소)', '상호', '고객구분', '사업용구분', '주민등록번호', '사업자번호', '계약상태(대)',
       '계약상태(중)', '설치주소', '계약시작일', '계약종료일', '영업구분', '추천경로',
       '영업본부명', '영업지사명', '영업자사번', '영업자명', '영업자연락처', '영업채널', '추천지사명',
       '유통망대분류', '유통망중분류', '추천자사번', '추천자명', '추천자유형', '정보제공자명', '청구본부명',
       '청구지사명', '합산여부', '수납구분', '청구번호', '청구주소', '정지시작일자', '종목', '업태', 'E-MAIL',
       '담당자', '휴대폰', '계약최초서비스게시일', '계약본부', '계약지사', '매출본사', '매출인정구분', '구역정보',
       '구역담당지점', '구역담당영업사원', '구역담당영업사원명', '시설구분', '요금구분', '실적본부', '실적지사',
       '실적최초등록일', '실적구분', '영업구역정보', '기술구역정보', '해지코드', '해지사유', '사용일수', '사용개월수',
       '매출구분', '영업본부2', '영업지사2', '실적채널', '실적부서', 'KTT월정료(조정)', 'KT월정료(조정)',
       '고알프', '제외사유']

In [22]:
# df에서 new_coluns 리스트의 컬럼들만 뽑아서 다시 저장해 줍니다.
df = df[new_columns]

In [23]:
df.head(3)

,관리본부명,관리지사명,고객번호,고객명,계약번호,서비스번호,서비스(대),서비스(중),서비스(소),상호,...,사용개월수,매출구분,영업본부2,영업지사2,실적채널,실적부서,KTT월정료(조정),KT월정료(조정),고알프,제외사유
0,서부본부,강서지사,276368,문*권,20296654,20296654,기본서비스,텔레캅아이,ktt OCT 가드(DVR),서울치즈양천(OCT),...,,,,,SP,강서지사,40914,0,N,
1,서부본부,인천지사,30624766,김*임,20296805,20296805,기본서비스,텔레캅아이,ktt OCT 가드(DVR),모아7080(OCT),...,,,,,SP,인천지사,56000,0,N,
2,강남/서부본부,평택지사,276716,강*욱,20297064,20297064,기본서비스,GiGAeyes Basic,GiGAeyes Basic,연세프라임이비인후과,...,,,,,SP,평택지사,49000,0,N,

In [24]:

# 패키지 변경 전: import pandas_profiling

from ydata_profiling import ProfileReport # 패키지 변경 후

In [25]:
# 불러온 데이터프레임에 대한 레포트 생성하기
# 패키지 변경 전: report = df.profile_report()

report = ProfileReport(df) # 패키지 변경 후

In [26]:
# 레포트를 실행하여 확인하기
report

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Exception ignored in: <bound method IPythonKernel._clean_thread_parent_frames of <ipykernel.ipkernel.IPythonKernel object at 0x000002044DEEC050>>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 785, in _clean_thread_parent_frames
    active_threads = {thread.ident for thread in threading.enumerate()}
                                                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\Python_v1\Lib\threading.py", line 1533, in enumerate
    def enumerate():

KeyboardInterrupt:

KeyboardInterrupt

In [ ]:
# 레포트 파일로 저장하기
report.to_file('./4월유지마감_ratings_report.html')

# GUI 적용

In [1]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# 파일 경로 설정
file_path = 'D:/시설/유지/24년 4월 유지가입자.cs'

# CSV 파일 읽기, 모든 데이터를 문자열로 처리
df = pd.read_csv(file_path, encoding='cp949', dtype=str)
df.fillna('', inplace=True)  # NaN 값을 빈 문자열로 대체

# 입력 위젯 설정
input_fields = {
    '계약번호': '계약 번호 입력',
    '상호': '상호 부분 입력',
    '실적최초등록일': '실적최초등록일 부분 입력',
    '고객명': '고객명 부분 입력',
    '설치주소': '설치 주소 부분 입력',
    '관리본부명': '관리 본부명 입력',
    '관리지사명': '관리 지사명 입력',
    '시설구분': '시설대상 입력',
    '요금구분': '요금대상 입력',
    '제외사유': '제외사유 대상입력',
    '영업자명': '구역 담당 영업사원 입력',
    '무인매장구분': '무인매장구분 입력',
    '무인매장업종구분': '무인매장업종구분 입력'
}

# 제외할 컬럼 목록 정의
excluded_columns = [
    "관리본부코드", "관리지사코드", "영상전환일", "서비스상태(대)", "서비스상태(중)",
    "접속전화번호", "설치우편번호", "견적월정료", "할인율", "월정료면제사유",
    "면제시작일", "면제종료일", "계약보증금", "보증금면제사유", "판매상품비", "견적설치공사비",
    "설치공사할부개월", "계약공사비", "면제공사비", "실징수액", "추천구분", "영업본부코드",
    "영업지사코드", "영업지점명", "모집유형", "추천본부코드", "추천본부명", "추천지사코드",
    "유통망소분류", "추천채널", "정보제공자부서", "정보제공자사번", "정보제공자연락처",
    "청구본부코드", "청구지사코드", "청구자명", "세금계산서발행여부", "계산서발행여부", "선후납구분",
    "청구전화번호", "청구우편번호", "청약일자", "청약취소일자", "공사희망일", "공사완료일",
    "준공완료일", "관제개통일", "서비스개시일", "서비스재개시일", "공사의뢰유형", "회선방식(대)",
    "회선방식(중)", "MUX", "전용회선번호", "MIN번호", "해지일자", "업종_대", "업종_중",
    "보험등급", "비고", "결합구분", "결합상품명", "결합약정개월수", "결합시작일", "금융기관코드",
    "면책구분", "타사전환", "이전고객번호", "전입신규여부", "고객추가정보", "청약취소사유",
    "정지기간", "정지유형", "설치공사비", "영업이익율", "공헌이익율","SW주장치안정화DB",
    "선장품", "브랜드", "A/S운용기간", "고객계약유형","판매할부개월",
    "최종계약구분", "KT마스터ID", "BIZNARU계약ID", "정지희망종료일", "신규PP","직접/추천",
    "판매구분"
]

# 데이터프레임에서 이 컬럼들을 제거
df = df.drop(columns=[col for col in excluded_columns if col in df.columns])

inputs = {key: widgets.Text(placeholder=desc, description=f'{key}:') for key, desc in input_fields.items()}

# 체크박스와 컬럼 이름 구성
checkboxes = [widgets.Checkbox(value=False, description=label) for label in df.columns]
checkbox_container = widgets.VBox(children=[widgets.HBox(checkboxes[i:i+5]) for i in range(0, len(checkboxes), 5)])

# 전체 선택/해제 버튼
toggle_buttons = widgets.ToggleButtons(
    options=['Select All', 'Deselect All'],
    description='Check:',
    disabled=False,
    button_style='',  # 'success', 'info', 'warning', 'danger' or ''
)

def toggle_checkboxes(change):
    if change['new'] == 'Select All':
        for checkbox in checkboxes:
            checkbox.value = True
    elif change['new'] == 'Deselect All':
        for checkbox in checkboxes:
            checkbox.value = False
    toggle_buttons.value = None  # Reset toggle button state

toggle_buttons.observe(toggle_checkboxes, 'value')

# 실행 버튼
run_button = widgets.Button(description='조회 실행', button_style='success', icon='search')
# 저장 버튼
save_button = widgets.Button(description='Excel로 저장', button_style='info', icon='save')

output = widgets.Output()

def run_query(b):
    global filtered_data, selected_columns
    with output:
        clear_output(wait=True)
        try:
            condition = True
            for field, widget in inputs.items():
                if widget.value.strip():
                    condition &= df[field].str.contains(widget.value.strip(), case=False)
            filtered_data = df.loc[condition]
            selected_columns = [cb.description for cb in checkboxes if cb.value]
            if not selected_columns:
                raise ValueError("결과로 표시할 컬럼을 선택하세요.")
            if filtered_data.empty:
                raise ValueError("조회된 데이터가 없습니다. 조건을 확인해주세요.")
            styled_html = filtered_data[selected_columns].to_html(escape=False, classes='styledTable')
            styled_css = """
            <style>
                .styledTable {
                    width: 100%;
                    border-collapse: collapse;
                    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
                    background-color: #f9f9f9;
                    color: #333;
                }
                .styledTable th, .styledTable td {
                    border: 1px solid #dddddd;
                    padding: 8px;
                    text-align: left;
                }
                .styledTable th {
                    background-color: #f2f2f2;
                    color: #333;
                }
                .styledTable tr:nth-child(even) {
                    background-color: #ffffff;
                }
                .styledTable tr:nth-child(odd) {
                    background-color: #f7f7f7;
                }
                .styledTable tr:hover {
                    background-color: #f1f1f1;
                }
            </style>
            """
            display(HTML(styled_css + styled_html))
        except Exception as e:
            display(HTML(f"<div style='color: red;'>Error: {e}</div>"))

def save_to_excel(b):
    global filtered_data, selected_columns
    try:
        if 'filtered_data' in globals() and 'selected_columns' in globals():
            filtered_data[selected_columns].to_excel('추출리스트.xlsx', index=False)
            with output:
                clear_output(wait=True)
                display(HTML("<div style='color: green;'>Data successfully saved to '추출리스트.xlsx'</div>"))
        else:
            raise ValueError("저장할 데이터가 없습니다. 먼저 조회를 실행하세요.")
    except Exception as e:
        with output:
            clear_output(wait=True)
            display(HTML(f"<div style='color: red;'>Error saving file: {e}</div>"))

# 이벤트 핸들러 연결
run_button.on_click(run_query)
save_button.on_click(save_to_excel)

# 입력 필드와 버튼을 같은 행에 배치
input_row = widgets.HBox([widgets.VBox([inputs[field] for field in inputs.keys()]), widgets.VBox([run_button, save_button])])

# 체크박스 토글과 컬럼 선택을 관리하는 행
checkbox_toggle_row = widgets.HBox([toggle_buttons])

# UI 구성
ui = widgets.VBox([input_row, checkbox_toggle_row, checkbox_container, output])
display(ui)

VBox(children=(HBox(children=(VBox(children=(Text(value='', description='계약번호:', placeholder='계약 번호 입력'), Text…

# 5월마감 유지

In [1]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# 파일 경로 설정
file_path = 'D:/시설/유지/24년5월 조건요약.cs'

# CSV 파일 읽기, 모든 데이터를 문자열로 처리
df = pd.read_csv(file_path, encoding='cp949', dtype=str)
df.fillna('', inplace=True)  # NaN 값을 빈 문자열로 대체

# 입력 위젯 설정
input_fields = {
    '청구번호': '청구 번호 입력',
    '계약번호': '계약 번호 입력',
    '상호': '상호 부분 입력',
    '실적최초등록일': '실적최초등록일 부분 입력',
    '고객명': '고객명 부분 입력',
    '설치주소': '설치 주소 부분 입력',
    '관리본부명': '관리 본부명 입력',
    '관리지사명': '관리 지사명 입력',
    '시설구분': '시설대상 입력',
    '요금구분': '요금대상 입력',
    '제외사유': '제외사유 대상입력',
    '영업자명': '구역 담당 영업사원 입력',
    '무인매장구분': '무인매장구분 입력',
    '무인매장업종구분': '무인매장업종구분 입력'
}

# 제외할 컬럼 목록 정의
excluded_columns = [
    "관리본부코드", "관리지사코드", "영상전환일", "서비스상태(대)", "서비스상태(중)",
    "접속전화번호", "설치우편번호", "견적월정료", "할인율", "월정료면제사유",
    "면제시작일", "면제종료일", "계약보증금", "보증금면제사유", "판매상품비", "견적설치공사비",
    "설치공사할부개월", "계약공사비", "면제공사비", "실징수액", "추천구분", "영업본부코드",
    "영업지사코드", "영업지점명", "모집유형", "추천본부코드", "추천본부명", "추천지사코드",
    "유통망소분류", "추천채널", "정보제공자부서", "정보제공자사번", "정보제공자연락처",
    "청구본부코드", "청구지사코드", "청구자명", "세금계산서발행여부", "계산서발행여부", "선후납구분",
    "청구전화번호", "청구우편번호", "청약일자", "청약취소일자", "공사희망일", "공사완료일",
    "준공완료일", "관제개통일", "서비스개시일", "서비스재개시일", "공사의뢰유형", "회선방식(대)",
    "회선방식(중)", "MUX", "전용회선번호", "MIN번호", "해지일자", "업종_대", "업종_중",
    "비고", "결합구분", "결합상품명", "결합약정개월수", "결합시작일", "금융기관코드",
    "면책구분", "타사전환", "이전고객번호", "전입신규여부", "고객추가정보", "청약취소사유",
    "정지기간", "정지유형", "설치공사비", "영업이익율", "공헌이익율","SW주장치안정화DB",
    "선장품", "브랜드", "A/S운용기간", "고객계약유형","판매할부개월",
    "최종계약구분", "KT마스터ID", "BIZNARU계약ID", "정지희망종료일", "신규PP","직접/추천",
    "판매구분"
]

# 데이터프레임에서 이 컬럼들을 제거
df = df.drop(columns=[col for col in excluded_columns if col in df.columns])

inputs = {key: widgets.Text(placeholder=desc, description=f'{key}:') for key, desc in input_fields.items()}

# 체크박스와 컬럼 이름 구성
checkboxes = [widgets.Checkbox(value=False, description=label) for label in df.columns]
checkbox_container = widgets.VBox(children=[widgets.HBox(checkboxes[i:i+5]) for i in range(0, len(checkboxes), 5)])

# 전체 선택/해제 버튼
toggle_buttons = widgets.ToggleButtons(
    options=['Select All', 'Deselect All'],
    description='Check:',
    disabled=False,
    button_style='',  # 'success', 'info', 'warning', 'danger' or ''
)

def toggle_checkboxes(change):
    if change['new'] == 'Select All':
        for checkbox in checkboxes:
            checkbox.value = True
    elif change['new'] == 'Deselect All':
        for checkbox in checkboxes:
            checkbox.value = False
    toggle_buttons.value = None  # Reset toggle button state

toggle_buttons.observe(toggle_checkboxes, 'value')

# 실행 버튼
run_button = widgets.Button(description='조회 실행', button_style='success', icon='search')
# 저장 버튼
save_button = widgets.Button(description='Excel로 저장', button_style='info', icon='save')

output = widgets.Output()

def run_query(b):
    global filtered_data, selected_columns
    with output:
        clear_output(wait=True)
        try:
            condition = True
            for field, widget in inputs.items():
                if widget.value.strip():
                    condition &= df[field].str.contains(widget.value.strip(), case=False)
            filtered_data = df.loc[condition]
            selected_columns = [cb.description for cb in checkboxes if cb.value]
            if not selected_columns:
                raise ValueError("결과로 표시할 컬럼을 선택하세요.")
            if filtered_data.empty:
                raise ValueError("조회된 데이터가 없습니다. 조건을 확인해주세요.")
            styled_html = filtered_data[selected_columns].to_html(escape=False, classes='styledTable')
            styled_css = """
            <style>
                .styledTable {
                    width: 100%;
                    border-collapse: collapse;
                    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
                    background-color: #f9f9f9;
                    color: #333;
                }
                .styledTable th, .styledTable td {
                    border: 1px solid #dddddd;
                    padding: 8px;
                    text-align: left;
                }
                .styledTable th {
                    background-color: #f2f2f2;
                    color: #333;
                }
                .styledTable tr:nth-child(even) {
                    background-color: #ffffff;
                }
                .styledTable tr:nth-child(odd) {
                    background-color: #f7f7f7;
                }
                .styledTable tr:hover {
                    background-color: #f1f1f1;
                }
            </style>
            """
            display(HTML(styled_css + styled_html))
        except Exception as e:
            display(HTML(f"<div style='color: red;'>Error: {e}</div>"))

def save_to_excel(b):
    global filtered_data, selected_columns
    try:
        if 'filtered_data' in globals() and 'selected_columns' in globals():
            filtered_data[selected_columns].to_excel('추출리스트.xlsx', index=False)
            with output:
                clear_output(wait=True)
                display(HTML("<div style='color: green;'>Data successfully saved to '추출리스트.xlsx'</div>"))
        else:
            raise ValueError("저장할 데이터가 없습니다. 먼저 조회를 실행하세요.")
    except Exception as e:
        with output:
            clear_output(wait=True)
            display(HTML(f"<div style='color: red;'>Error saving file: {e}</div>"))

# 이벤트 핸들러 연결
run_button.on_click(run_query)
save_button.on_click(save_to_excel)

# 입력 필드와 버튼을 같은 행에 배치
input_row = widgets.HBox([widgets.VBox([inputs[field] for field in inputs.keys()]), widgets.VBox([run_button, save_button])])

# 체크박스 토글과 컬럼 선택을 관리하는 행
checkbox_toggle_row = widgets.HBox([toggle_buttons])

# UI 구성
ui = widgets.VBox([input_row, checkbox_toggle_row, checkbox_container, output])
display(ui)

VBox(children=(HBox(children=(VBox(children=(Text(value='', description='청구번호:', placeholder='청구 번호 입력'), Text…

In [6]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# 파일 경로 설정
file_path = 'D:/시설/유지/24년5월 조건요약.cs'

# CSV 파일 읽기, 모든 데이터를 문자열로 처리
df = pd.read_csv(file_path, encoding='cp949', dtype=str)
df.fillna('', inplace=True)  # NaN 값을 빈 문자열로 대체

# 계약최초서비스개시일 변환
df['계약최초서비스개시일'] = pd.to_datetime(df['계약최초서비스개시일'], format='%Y%m%d%H%M%S', errors='coerce').dt.strftime('%Y-%m-%d')
df['계약최초서비스개시일'].fillna('', inplace=True)  # NaT 값을 빈 문자열로 대체

# 입력 위젯 설정
input_fields = {
    '계약번호': '계약 번호 입력',
    '상호': '상호 부분 입력',
    '실적최초등록일': '실적최초등록일 부분 입력',
    '고객명': '고객명 부분 입력',
    '설치주소': '설치 주소 부분 입력',
    '관리본부명': '관리 본부명 입력',
    '관리지사명': '관리 지사명 입력',
    '시설구분': '시설대상 입력',
    '요금구분': '요금대상 입력',
    '제외사유': '제외사유 대상입력',
    '영업자명': '구역 담당 영업사원 입력',
    '무인매장구분': '무인매장구분 입력',
    '무인매장업종구분': '무인매장업종구분 입력'
}

# 제외할 컬럼 목록 정의
excluded_columns = [
    "관리본부코드", "관리지사코드", "영상전환일", "서비스상태(대)", "서비스상태(중)",
    "접속전화번호", "설치우편번호", "견적월정료", "할인율", "월정료면제사유",
    "면제시작일", "면제종료일", "계약보증금", "보증금면제사유", "판매상품비", "견적설치공사비",
    "설치공사할부개월", "계약공사비", "면제공사비", "실징수액", "추천구분", "영업본부코드",
    "영업지사코드", "영업지점명", "모집유형", "추천본부코드", "추천본부명", "추천지사코드",
    "유통망소분류", "추천채널", "정보제공자부서", "정보제공자사번", "정보제공자연락처",
    "청구본부코드", "청구지사코드", "청구자명", "세금계산서발행여부", "계산서발행여부", "선후납구분",
    "청구전화번호", "청구우편번호", "청약일자", "청약취소일자", "공사희망일", "공사완료일",
    "준공완료일", "관제개통일", "서비스개시일", "서비스재개시일", "공사의뢰유형", "회선방식(대)",
    "회선방식(중)", "MUX", "전용회선번호", "MIN번호", "해지일자", "업종_대", "업종_중",
    "보험등급", "비고", "결합구분", "결합상품명", "결합약정개월수", "결합시작일", "금융기관코드",
    "면책구분", "타사전환", "이전고객번호", "전입신규여부", "고객추가정보", "청약취소사유",
    "정지기간", "정지유형", "설치공사비", "영업이익율", "공헌이익율","SW주장치안정화DB",
    "선장품", "브랜드", "A/S운용기간", "고객계약유형","판매할부개월",
    "최종계약구분", "KT마스터ID", "BIZNARU계약ID", "정지희망종료일", "신규PP","직접/추천",
    "판매구분"
]

# 데이터프레임에서 이 컬럼들을 제거
df = df.drop(columns=[col for col in excluded_columns if col in df.columns])

inputs = {key: widgets.Text(placeholder=desc, description=f'{key}:') for key, desc in input_fields.items()}

# 체크박스와 컬럼 이름 구성
checkboxes = [widgets.Checkbox(value=False, description=label) for label in df.columns]
checkbox_container = widgets.VBox(children=[widgets.HBox(checkboxes[i:i+5]) for i in range(0, len(checkboxes), 5)])

# 전체 선택/해제 버튼
toggle_buttons = widgets.ToggleButtons(
    options=['Select All', 'Deselect All'],
    description='Check:',
    disabled=False,
    button_style='',  # 'success', 'info', 'warning', 'danger' or ''
)

def toggle_checkboxes(change):
    if change['new'] == 'Select All':
        for checkbox in checkboxes:
            checkbox.value = True
    elif change['new'] == 'Deselect All':
        for checkbox in checkboxes:
            checkbox.value = False
    toggle_buttons.value = None  # Reset toggle button state

toggle_buttons.observe(toggle_checkboxes, 'value')

# 실행 버튼
run_button = widgets.Button(description='조회 실행', button_style='success', icon='search')
# 저장 버튼
save_button = widgets.Button(description='Excel로 저장', button_style='info', icon='save')

output = widgets.Output()

def run_query(b):
    global filtered_data, selected_columns
    with output:
        clear_output(wait=True)
        try:
            condition = True
            for field, widget in inputs.items():
                if widget.value.strip():
                    condition &= df[field].str.contains(widget.value.strip(), case=False)
            filtered_data = df.loc[condition]
            selected_columns = [cb.description for cb in checkboxes if cb.value]
            if not selected_columns:
                raise ValueError("결과로 표시할 컬럼을 선택하세요.")
            if filtered_data.empty:
                raise ValueError("조회된 데이터가 없습니다. 조건을 확인해주세요.")
            styled_html = filtered_data[selected_columns].to_html(escape=False, classes='styledTable')
            styled_css = """
            <style>
                .styledTable {
                    width: 100%;
                    border-collapse: collapse;
                    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
                    background-color: #f9f9f9;
                    color: #333;
                }
                .styledTable th, .styledTable td {
                    border: 1px solid #dddddd;
                    padding: 8px;
                    text-align: left;
                }
                .styledTable th {
                    background-color: #f2f2f2;
                    color: #333;
                }
                .styledTable tr:nth-child(even) {
                    background-color: #ffffff;
                }
                .styledTable tr:nth-child(odd) {
                    background-color: #f7f7f7;
                }
                .styledTable tr:hover {
                    background-color: #f1f1f1;
                }
            </style>
            """
            display(HTML(styled_css + styled_html))
        except Exception as e:
            display(HTML(f"<div style='color: red;'>Error: {e}</div>"))

def save_to_excel(b):
    global filtered_data, selected_columns
    try:
        if 'filtered_data' in globals() and 'selected_columns' in globals():
            filtered_data[selected_columns].to_excel('추출리스트.xlsx', index=False)
            with output:
                clear_output(wait=True)
                display(HTML("<div style='color: green;'>Data successfully saved to '추출리스트.xlsx'</div>"))
        else:
            raise ValueError("저장할 데이터가 없습니다. 먼저 조회를 실행하세요.")
    except Exception as e:
        with output:
            clear_output(wait=True)
            display(HTML(f"<div style='color: red;'>Error saving file: {e}</div>"))

# 이벤트 핸들러 연결
run_button.on_click(run_query)
save_button.on_click(save_to_excel)

# 입력 필드와 버튼을 같은 행에 배치
input_row = widgets.HBox([widgets.VBox([inputs[field] for field in inputs.keys()]), widgets.VBox([run_button, save_button])])

# 체크박스 토글과 컬럼 선택을 관리하는 행
checkbox_toggle_row = widgets.HBox([toggle_buttons])

# UI 구성
ui = widgets.VBox([input_row, checkbox_toggle_row, checkbox_container, output])
display(ui)

KeyError: '계약최초서비스개시일'